name: Package and Publish to GitHub and NuGet

on:
 push:
  branches: ['main']

env:
 NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 SourceDirectory: './source'
 ProjectDirectory: './source/BenBurgers.Binary'
    
jobs:
 build:
  runs-on: ubuntu-latest
  permissions:
   contents: read
   packages: write

  steps:
   - name: Checkout repository
     uses: actions/checkout@v3
   - name: Setup .NET SDK 7.0.x
     uses: actions/setup-dotnet@v3
     with:
      dotnet-version: 7.0.x
   - name: Cache dependencies
     uses: actions/cache@v3
     with:
      path: ~/.nuget/packages
      key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      restore-keys: |
       ${{ runner.os }}-nuget
   - name: Install dependencies
     working-directory: ${{ env.SourceDirectory }}
     run: dotnet restore
   - name: Build
     working-directory: ${{ env.SourceDirectory }}
     run: dotnet build --configuration Release --no-restore
   - name: Test
     working-directory: ${{ env.SourceDirectory }}
     run: dotnet test --no-restore --verbosity normal
   - name: Create the package 'BenBurgers.Binary'
     working-directory: ${{ env.ProjectDirectory }}
     run: dotnet pack --configuration Release -p:PackageVersion=0.1.${{ github.run_number }}
   - name: Publish the package to GitHub Packages Registry
     working-directory: ${{ env.ProjectDirectory }}
     run: dotnet nuget push ./bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/benburgers/index.json
   - name: Publish the package to NuGet.org
     working-directory: ${{ env.ProjectDirectory }}
     run: dotnet nuget push ./bin/Release/*.nupkg --api-key ${{ secrets.NUGET_ACCESSTOKEN }} --source https://api.nuget.org/v3/index.json